import { NextRequest, NextResponse } from 'next/server'
import { createRouteClient } from '@/lib/supabase-server'
import { createServerClient } from '@/lib/supabase'
import { generateReferenceCode } from '@/lib/utils'
import { cookies } from 'next/headers'
// Email confirmation is currently disabled (commented out below). When
// re-enabled, re-import sendOrderSuccessEmail from '@/lib/email-service'.
import { sendOrderSuccessSMS, sendAdminAgentOrderAlert } from '@/lib/sms-service'
import { resolveOwnConfirmationSender } from '@/lib/sms-confirmation-sender'
import { waitUntil } from '@vercel/functions'
import { triggerFulfillment } from '@/lib/fulfillment-trigger'
import { shouldAutoFulfill, isMashupCategory } from '@/lib/mashup'
import { sendAdminPushNotification } from '@/lib/push-service'
import { getAdminOOSNetworks, isNetworkOOS } from '@/lib/network-stock'
import { resolveOwnerCost } from '@/lib/pricing/cost-basis'
import { resolveSubAgentContext } from '@/lib/sub-agent-account'
import { resolveSubAgentDataCost } from '@/lib/sub-agent-data-pricing'
import { hasSubAgentPricingConfigured } from '@/lib/sub-agent-pricing'
import { recordPendingSubAgentEarning } from '@/lib/sub-agent-earnings'
import { resolveOrderQueueing } from '@/lib/number-registration'
import { checkMtnWhitelistGate } from '@/lib/mtn-whitelist-gate'

export async function POST(request: NextRequest) {
    try {
        const cookieStore = await cookies()
        const supabaseUserClient = await createRouteClient()
        const { data: { user: authUser }, error: authError } = await supabaseUserClient.auth.getUser()

        if (authError || !authUser) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const user = authUser
        const userId = user.id

        let body: any;
        try {
            body = await request.json()
        } catch (e) {
            return NextResponse.json({ error: 'Invalid request body' }, { status: 400 })
        }

        // referenceCode is now generated by the frontend to act as an idempotency key.
        // If the same referenceCode is submitted twice, the second request will fail on
        // the unique constraint, preventing double orders.
        const { packageId, phoneNumber, referenceCode: clientReferenceCode } = body

        if (!packageId || typeof packageId !== 'string') {
            return NextResponse.json({ error: 'Package ID is required' }, { status: 400 })
        }
        // Bound the client-supplied idempotency key so it can't be used to store
        // an oversized payload in the orders table / idempotency lookup. 97 is just
        // a sane upper bound on a client-generated reference string — no downstream
        // RPC suffixes or otherwise transforms this value in the current sub-agent
        // earnings path, so there's no tighter cap to derive it from.
        if (clientReferenceCode !== undefined && (typeof clientReferenceCode !== 'string' || clientReferenceCode.length > 97)) {
            return NextResponse.json({ error: 'Invalid referenceCode' }, { status: 400 })
        }

        if (!phoneNumber || typeof phoneNumber !== 'string') {
            return NextResponse.json({ error: 'Phone number is required' }, { status: 400 })
        }

        const cleanPhone = phoneNumber.replace(/\s+/g, '')
        const ghanaPhoneRegex = /^(0\d{9}|233\d{9})$/

        if (!ghanaPhoneRegex.test(cleanPhone)) {
            return NextResponse.json({
                error: 'Invalid phone number format. Use Ghana format: 0XXXXXXXXX or 233XXXXXXXXX'
            }, { status: 400 })
        }

        // Service role client for privileged operations
        const supabase = createServerClient()

        // === IDEMPOTENCY: If a referenceCode was provided by the client, check for duplicates first ===
        if (clientReferenceCode) {
            // Scope the lookup to the authenticated user so a reference_code can
            // never surface another user's order details (cross-tenant disclosure).
            const { data: existingOrder } = await (supabase.from('orders') as any)
                .select('id, reference_code, status')
                .eq('reference_code', clientReferenceCode)
                .eq('user_id', userId)
                .maybeSingle()

            if (existingOrder) {
                // Order already exists — this is a duplicate request. Return success with existing data.
                console.log(`[Purchase] Duplicate request blocked for reference: ${clientReferenceCode}`)
                return NextResponse.json({
                    success: true,
                    isDuplicate: true,
                    order: {
                        id: existingOrder.id,
                        reference_code: existingOrder.reference_code,
                        status: existingOrder.status,
                    },
                })
            }
        }

        // Get package details
        const { data: pkg, error: pkgError } = await supabase
            .from('data_packages')
            .select('*')
            .eq('id', packageId)
            .eq('is_available', true)
            .single()

        if (pkgError || !pkg) {
            return NextResponse.json({ error: 'Package not found' }, { status: 404 })
        }

        // Per-network out-of-stock guard (admin/global). UI hiding is bypassable.
        const adminOOS = await getAdminOOSNetworks(supabase)
        if (isNetworkOOS(adminOOS, (pkg as any).network)) {
            return NextResponse.json(
                { error: `${(pkg as any).network} is out of stock at the moment` },
                { status: 409 },
            )
        }

        // Check if phone is blacklisted.
        // Use the normalized `cleanPhone` (whitespace stripped) — otherwise an
        // attacker could bypass the blacklist by inserting a space into the
        // number they submit.
        const { data: blacklisted } = await supabase
            .from('phone_blacklist')
            .select('id')
            .eq('phone_number', cleanPhone)
            .single()

        if (blacklisted) {
            return NextResponse.json({ error: 'This phone number is not allowed' }, { status: 400 })
        }

        // MTN AgentPortal whitelist gate: independent of the number-registration
        // queue system below — when the admin toggle is on, this blocks the
        // purchase outright (no charge, no order) for MTN numbers AgentPortal
        // hasn't whitelisted yet.
        const whitelistGate = await checkMtnWhitelistGate(cleanPhone, (pkg as any).network, (pkg as any).category)
        if (whitelistGate.blocked) {
            return NextResponse.json({ error: whitelistGate.reason }, { status: 400 })
        }

        // Get user role — fetch expiry fields to validate active subscription before granting agent pricing
        const { data: userRoleData } = await supabase
            .from('users')
            .select('role, status, dealer_expires_at, agent_expires_at')
            .eq('id', userId)
            .single()

        // Server-side suspension enforcement — the dashboard gate alone is bypassable.
        if ((userRoleData as any)?.status === 'suspended') {
            return NextResponse.json({ error: 'Your account is currently suspended. Please contact support.' }, { status: 403 })
        }

        const userRole = (userRoleData as any)?.role
        const _dealerExpired = (userRoleData as any)?.dealer_expires_at
            && new Date((userRoleData as any).dealer_expires_at) < new Date()
        const _agentExpired = (userRoleData as any)?.agent_expires_at
            && new Date((userRoleData as any).agent_expires_at) < new Date()
        const isActiveDealer = userRole === 'dealer' && !_dealerExpired
        const isActiveAgent = userRole === 'agent' && !_agentExpired
        const isAgent = isActiveAgent || isActiveDealer

        // Sub-agent purchase (spec §5.1): a sub buys at their recruiter-set price, and their
        // recruiter earns the markup — one party, one earning, no chain. Eligibility is
        // evaluated LIVE: a pending/suspended sub, or one whose recruiter is currently
        // ineligible, cannot transact.
        const subCtx = await resolveSubAgentContext(supabase, userId)
        if (subCtx.isSub && !subCtx.effectiveActive) {
            return NextResponse.json(
                { error: subCtx.inactiveReason || 'Your account is not currently active' },
                { status: 403 },
            )
        }

        // Buyer cost via the single shared resolver (lib/pricing/cost-basis) — expiry-aware.
        let priceToCharge = resolveOwnerCost(pkg as any, {
            role: userRole,
            agent_expires_at: (userRoleData as any)?.agent_expires_at,
            dealer_expires_at: (userRoleData as any)?.dealer_expires_at,
        })

        // Sub-agent pricing overrides the role price entirely (spec C2) — the sub's cost is
        // recruiter-derived, never role-derived. Fails closed before any charge (spec C7).
        let recruiterMargin: { recruiterId: string; amount: number } | null = null
        if (subCtx.isSub) {
            // Server-side teeth for spec C4's "unconfigured = unbuyable" guarantee (Task 11):
            // resolveSubAgentDataCost treats "no pricing configured" and "configured at zero
            // markup" identically (both resolve to markup=0), so the listing-page hide alone
            // doesn't stop a raw API call. Mashup is excluded — its markup is structurally
            // always zero (spec C9), nothing is ever "configured" for it, so it must never be
            // gated here (mirrors filterPackagesForSubAgent's own mashup exclusion). Uses the
            // shared isMashupCategory() helper, not a literal 'mashup' string — the real column
            // value is 'mtn_mashup' (lib/mashup.ts's MASHUP_CATEGORY); a literal mismatch here
            // once made this exemption never fire, 409-blocking every sub-agent mashup purchase
            // (final whole-plan review finding, fixed before merge).
            if (
                !isMashupCategory((pkg as any).category)
                && subCtx.recruiterId
                && !(await hasSubAgentPricingConfigured(supabase, subCtx.recruiterId, userId, 'data', packageId))
            ) {
                return NextResponse.json({ error: 'Pricing is not available for this package right now' }, { status: 409 })
            }

            const resolved = await resolveSubAgentDataCost(supabase, userId, packageId, pkg, (pkg as any).category)
            if (!resolved.ok) {
                console.error(`[Purchase] 🚨 sub cost unresolvable for pkg ${packageId} (user ${userId}): ${resolved.reason}`)
                return NextResponse.json({ error: 'Pricing is not available for this package right now' }, { status: 409 })
            }
            priceToCharge = resolved.subCost
            if (resolved.recruiterEarns > 0 && resolved.recruiterId) {
                recruiterMargin = { recruiterId: resolved.recruiterId, amount: resolved.recruiterEarns }
            }
        }

        // FIX D (spec §7.5) — wallet-path price floor: never charge a zero/invalid
        // amount (broken package row or resolver edge would otherwise ship free data).
        if (!Number.isFinite(priceToCharge) || priceToCharge <= 0) {
            console.error(`[Purchase] 🚨 Invalid priceToCharge ${priceToCharge} for pkg ${packageId} (user ${userId}) — blocked`)
            return NextResponse.json({ error: 'This package is temporarily unavailable' }, { status: 409 })
        }

        // === SECURITY: Atomic wallet deduction (prevents double-spend) ===
        const { data: deductResult, error: deductError } = await (supabase as any)
            .rpc('deduct_wallet_balance', {
                p_user_id: userId,
                p_amount: priceToCharge,
            })

        if (deductError) {
            if (deductError.message?.includes('INSUFFICIENT_BALANCE')) {
                return NextResponse.json({ error: 'Insufficient balance' }, { status: 400 })
            }
            console.error('Wallet deduction error:', deductError)
            return NextResponse.json({ error: 'Failed to process payment' }, { status: 500 })
        }

        const walletRow = deductResult?.[0] || deductResult
        const walletId = walletRow?.wallet_id
        const newBalance = walletRow?.new_balance

        if (!walletId) {
            return NextResponse.json({ error: 'Wallet not found' }, { status: 404 })
        }

        // Use client-provided referenceCode if available, else generate a new one
        const referenceCode = clientReferenceCode || generateReferenceCode()

        // MTN number-registration gate: an unregistered MTN recipient is HELD as
        // 'queued' (no dispatch) until the supplier confirms registration. Only
        // evaluated for auto-fulfillable categories (mashup is manual regardless).
        const queueDecision = shouldAutoFulfill((pkg as any).category)
            ? await resolveOrderQueueing(phoneNumber, (pkg as any).network)
            : { queue: false, canonicalPhone: null }

        // Create order AFTER successful deduction
        const { data: order, error: orderError } = await (supabase
            .from('orders') as any)
            .insert({
                user_id: userId,
                phone_number: phoneNumber,
                network: (pkg as any).network,
                size: (pkg as any).size,
                price: priceToCharge,
                cost_price_at_time: (pkg as any).cost_price || 0,
                role_at_time: (userRoleData as any)?.role || 'customer',
                status: queueDecision.queue ? 'queued' : 'pending',
                payment_status: 'paid',
                reference_code: referenceCode,
                fulfillment_method: shouldAutoFulfill((pkg as any).category) ? 'auto' : 'manual',
                category: (pkg as any).category || 'data',
            })
            .select()
            .single()

        if (orderError) {
            console.error('Order creation error:', orderError)
            // Refund the deducted amount since order failed. Use the atomic
            // credit RPC (relative increment) — NOT an absolute SET — so a
            // concurrent deduction/credit can't be silently clobbered (TOCTOU).
            const { error: refundError } = await (supabase as any)
                .rpc('credit_wallet_balance', {
                    p_user_id: userId,
                    p_amount: priceToCharge,
                })
            if (refundError) {
                console.error(`[Purchase] CRITICAL: refund failed for ${referenceCode}, manual reconciliation required:`, refundError)
            }
            return NextResponse.json({ error: 'Failed to create order' }, { status: 500 })
        }

        // Sub-agent purchase: credit the ONE direct recruiter (spec C3, C4 — a pending row now,
        // credited by the trigger only once the order actually completes). Never blocks the
        // purchase — the sub already paid, the data must still ship.
        if (recruiterMargin) {
            await recordPendingSubAgentEarning(supabase, {
                orderReference: referenceCode,
                orderTable: 'orders',
                recruiterId: recruiterMargin.recruiterId,
                subUserId: userId,
                amount: recruiterMargin.amount,
            }).catch((e) => console.error('[Purchase] recordPendingSubAgentEarning threw:', e))
        }

        // === PERFORMANCE: Create wallet transaction (non-blocking, fire-and-forget) ===
        ;(supabase.from('wallet_transactions') as any).insert({
            wallet_id: walletId,
            user_id: userId,
            type: 'debit',
            amount: priceToCharge,
            description: `Data purchase: ${(pkg as any).size} for ${phoneNumber}`,
            reference: referenceCode,
            source: 'purchase',
            status: 'completed',
        }).then(() => {}).catch((e: any) => console.error('[Purchase] Tx insert error:', e))

        // === PERFORMANCE: Create notification (fire-and-forget) ===
        ;(supabase.from('notifications') as any).insert({
            user_id: userId,
            title: 'Order Placed',
            message: `Your order for ${(pkg as any).size} to ${phoneNumber} has been placed and is being processed.`,
            type: 'order_update',
            action_url: `/dashboard/my-orders`,
        }).then(() => {}).catch((e: any) => console.error('[Purchase] Notification error:', e))

        // === NOTIFICATIONS & AUTO-FULFILLMENT: Wrapped in waitUntil to prevent Vercel freeze ===
        waitUntil((async () => {
            try {
                // Fetch user data once for both notifications and fulfillment
                const { data: userData, error: userFetchError } = await supabase
                    .from('users')
                    .select('email, first_name, last_name, phone_number, role, order_success_sms_enabled')
                    .eq('id', userId)
                    .single()

                if (userFetchError || !userData) {
                    console.error('[Purchase] Post-purchase user fetch failed:', userFetchError)
                } else {
                    const userEmail = (userData as any).email
                    const firstName = (userData as any).first_name || 'Customer'
                    const accountHolderPhone = (userData as any).phone_number

                    // 1. Send User Email Confirmation (Removed as requested)
                    // if (userEmail) {
                    //     await sendOrderSuccessEmail(...)
                    // }

                    // 2. Send User SMS Confirmation (To data recipient as requested)
                    //    Honour the buyer's per-user opt-out (defaults to enabled).
                    if (accountHolderPhone && (userData as any).order_success_sms_enabled !== false && !queueDecision.queue) {
                        // KFT SMS v2: resolve the buyer's OWN approved sender for THEIR OWN
                        // order confirmation. USSD and shop-customer confirmations stay on
                        // the platform sender — out of scope here (resolution never throws).
                        const ownSender = await resolveOwnConfirmationSender(supabase, userId)
                        await sendOrderSuccessSMS(accountHolderPhone, {
                            network: (pkg as any).network,
                            size: (pkg as any).size,
                            price: priceToCharge,
                            recipientNumber: phoneNumber,
                            currentBalance: newBalance,
                            sender: ownSender ?? undefined
                        }).then(() => console.log('[Purchase] Confirmation SMS sent successfully'))
                          .catch((err: Error) => console.error('[Purchase] Confirmation SMS failed:', err))
                    }

                    // 3. Send Admin Agent Alert
                    if (isAgent) {
                        await sendAdminAgentOrderAlert()
                            .catch((err: Error) => console.error('[Purchase] Admin agent alert failed:', err))
                    }

                    // 4. Trigger Auto-Fulfillment (skip manual-fulfillment categories e.g. mtn_mashup)
                    if (queueDecision.queue) {
                        // Unregistered MTN number — held as 'queued'. No dispatch until an
                        // admin releases the batch after the supplier confirms registration.
                        console.log(`[Purchase] Order ${(order as any).id} QUEUED for MTN number registration — fulfillment & success SMS held`)
                    } else if (shouldAutoFulfill((pkg as any).category)) {
                        await triggerFulfillment((order as any).id, (pkg as any).network, {
                            email: userEmail || 'Unknown',
                            name: `${firstName} ${(userData as any).last_name || ''}`.trim() || 'Customer'
                        })
                    } else {
                        console.log(`[Purchase] Auto-fulfillment suppressed for manual category=${(pkg as any).category}, order=${(order as any).id}`)
                        // Manual-fulfillment categories (Special MTN Mashup) get no auto-fulfillment,
                        // so alert admins via web push + in-app notification to process the order.
                        if (isMashupCategory((pkg as any).category)) {
                            await sendAdminPushNotification({
                                title: 'New Special MTN Mashup Order',
                                body: `${(pkg as any).size} (GHS ${Number(priceToCharge).toFixed(2)}) for ${phoneNumber} — needs manual fulfillment.`,
                                url: '/admin/mtn-mashup',
                            }).catch((err: Error) => console.error('[Purchase] Mashup admin push failed:', err))
                        }
                    }
                }
            } catch (postPurchaseError) {
                console.error('[Purchase] Post-purchase notification/fulfillment failed:', postPurchaseError)
            }
        })())

        // Return immediately — don't wait for fulfillment/emails/SMS
        return NextResponse.json({
            success: true,
            order: {
                id: (order as any).id,
                reference_code: referenceCode,
                status: queueDecision.queue ? 'queued' : 'pending',
                network: (pkg as any).network,
                size: (pkg as any).size,
                phone_number: phoneNumber,
                price: priceToCharge,
                new_balance: newBalance,
            },
        })
    } catch (error) {
        console.error('Purchase error:', error)
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
    }
}

async function updateCustomerPurchases(
    supabase: any,
    userId: string,
    phoneNumber: string,
    amount: number
) {
    const { data: existing } = await supabase
        .from('customer_purchases')
        .select('*')
        .eq('user_id', userId)
        .eq('customer_phone', phoneNumber)
        .single()

    if (existing) {
        await supabase
            .from('customer_purchases')
            .update({
                total_purchases: existing.total_purchases + 1,
                total_spent: existing.total_spent + amount,
                last_purchase_at: new Date().toISOString(),
            })
            .eq('id', existing.id)
    } else {
        await supabase.from('customer_purchases').insert({
            user_id: userId,
            customer_phone: phoneNumber,
            total_purchases: 1,
            total_spent: amount,
            first_purchase_at: new Date().toISOString(),
            last_purchase_at: new Date().toISOString(),
        })
    }
}
