-- supabase/migrations/20260615_ussd_activate_wallet_or_profit.sql
-- =============================================================================
-- USSD shop activation — pay from WALLET or PROFIT (atomic)
-- =============================================================================
-- Mirrors activate_shop_sms (20260612_shop_phase_c.sql): a single transaction
-- performs the debit AND the activation, so the legacy "money taken but not
-- activated" gap in the route is closed.
--
-- Money safety:
--   * The fee is read server-side from admin_settings — NEVER trusted from the
--     caller.
--   * The candidate USSD code is generated by the route (lib/ussd/code-generator)
--     and passed in. On a UNIQUE(ussd_code) collision the function raises
--     CODE_TAKEN; re-raising aborts the whole function transaction, rolling back
--     the debit too — so a colliding retry can neither double-charge nor lose
--     money.
--   * SECURITY DEFINER + service_role-only EXECUTE prevents spoofed owner IDs.
--
-- Profit spend is a bare shop_wallets UPDATE with no ledger row — consistent
-- with activate_shop_sms (shop_wallet_transactions.type only allows
-- 'profit' | 'withdrawal', so a profit-SPEND ledger row is out of scope).
-- =============================================================================

CREATE OR REPLACE FUNCTION public.activate_shop_ussd(
    p_owner_id  UUID,
    p_paid_from TEXT,
    p_code      TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_shop       shop_profiles%ROWTYPE;
    v_fee        NUMERIC;
    v_rows       INTEGER;
    v_constraint TEXT;
BEGIN
    IF p_paid_from NOT IN ('wallet', 'profit') THEN
        RAISE EXCEPTION 'INVALID_SOURCE';
    END IF;

    SELECT * INTO v_shop FROM shop_profiles WHERE owner_id = p_owner_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'SHOP_NOT_FOUND';
    END IF;

    IF v_shop.approval_status <> 'approved' OR COALESCE(v_shop.is_active, false) = false THEN
        RAISE EXCEPTION 'SHOP_NOT_APPROVED';
    END IF;

    -- Idempotent: if a code was EVER assigned, treat the shop as already
    -- activated and charge nothing — even if ussd_active was later toggled off
    -- (e.g. an admin suspension). This prevents a re-activation from
    -- double-charging the owner AND from overwriting a code customers already
    -- know. (A deliberate paid re-activation after suspension, if ever needed,
    -- should be a separate explicit RPC.)
    IF v_shop.ussd_code IS NOT NULL THEN
        RETURN jsonb_build_object(
            'success',        true,
            'code',           v_shop.ussd_code,
            'already_active', true,
            'amount_paid',    0
        );
    END IF;

    -- Fee from admin config only. admin_settings.value is JSONB stored as a
    -- quoted string e.g. "50.00" — strip the surrounding quotes before casting.
    SELECT COALESCE(NULLIF(trim(both '"' from value::text), '')::numeric, 50)
      INTO v_fee
      FROM admin_settings
     WHERE key = 'ussd_shop_activation_fee';
    IF v_fee IS NULL THEN
        v_fee := 50;
    END IF;
    IF v_fee < 0 THEN
        RAISE EXCEPTION 'INVALID_FEE';
    END IF;

    -- Atomic debit from the chosen balance (skipped when the fee is 0).
    IF v_fee > 0 THEN
        IF p_paid_from = 'wallet' THEN
            UPDATE wallets
               SET balance     = balance - v_fee,
                   total_spent = COALESCE(total_spent, 0) + v_fee,
                   updated_at  = now()
             WHERE user_id = p_owner_id AND balance >= v_fee;
        ELSE
            UPDATE shop_wallets
               SET balance    = balance - v_fee,
                   updated_at = now()
             WHERE owner_id = p_owner_id AND balance >= v_fee;
        END IF;
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        IF v_rows = 0 THEN
            RAISE EXCEPTION 'INSUFFICIENT_BALANCE';
        END IF;
    END IF;

    -- Activate. A UNIQUE(ussd_code) collision raises CODE_TAKEN; re-raising it
    -- aborts the transaction and rolls back the debit above, so the route can
    -- safely retry with a fresh candidate. Scope the handler to the ussd_code
    -- constraint specifically — any OTHER future unique violation must surface
    -- immediately (not be retried, which would re-run the debit).
    BEGIN
        UPDATE shop_profiles
           SET ussd_code         = p_code,
               ussd_active       = true,
               ussd_activated_at = now(),
               updated_at        = now()
         WHERE id = v_shop.id;
    EXCEPTION WHEN unique_violation THEN
        GET STACKED DIAGNOSTICS v_constraint = CONSTRAINT_NAME;
        IF v_constraint ILIKE '%ussd_code%' THEN
            RAISE EXCEPTION 'CODE_TAKEN';
        ELSE
            RAISE;
        END IF;
    END;

    RETURN jsonb_build_object(
        'success',        true,
        'code',           p_code,
        'already_active', false,
        'amount_paid',    v_fee
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.activate_shop_ussd(UUID, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.activate_shop_ussd(UUID, TEXT, TEXT) TO service_role;
